### ISSUE TITLE
Show help info when `workspace` is called with no subcommands

### ISSUE THREAD

**Issue by roma0615** [matthias-t/workspace#25]
If you run just `workspace` with no subcommands, nothing happens. I think this could be misleading for new users. I understand that the next logical step would be to run `workspace -h`, but wouldn't it make more sense to also display the help information when no subcommands are provided?

**Comment by matthias-t** [comment]
I thought we could make it default to opening the last workspace you opened, so if you turn your computer off, you can quickly resume where you left off by typing `ws`

**Comment by roma0615** [comment]
That works too
