### ISSUE TITLE
Formatting in output is lost when using `ws` command in place of `workspace`

### ISSUE THREAD

**Issue by roma0615** [matthias-t/workspace#27]
When using the `ws` command instead of `workspace`. If your terminal supports color output, that is lost too.

If I run `workspace ls`:
```
main-ws                     /Users/roma/Documents/Rust/workspace
myws                        /Users/roma/Documents/Rust/workspace
really-long-workspace-name  /Users/roma/Documents/Rust/workspace
```
the indenting is correct. When I run `ws ls`, I get:
```
main-ws /Users/roma/Documents/Rust/workspace
myws /Users/roma/Documents/Rust/workspace
really-long-workspace-name /Users/roma/Documents/Rust/workspace
```

Another example:
`workspace new -h`:
```
workspace-new 
Creates a new workspace in this directory

USAGE:
    workspace new <NAME>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <NAME>    Name of the new workspace
```

`ws new -h`:
```
workspace-new
Creates a new workspace in this directory

USAGE:
workspace new <NAME>

FLAGS:
-h, --help Prints help information
-V, --version Prints version information

ARGS:
<NAME> Name of the new workspace
```

**Comment by matthias-t** [comment]
I can confirm it doesn't happen on cmd and PowerShell. When you fixed the sourcing problem with bash, you removed the quotes around `$line` here:
https://github.com/matthias-t/workspace/blob/febe5511bac8240df13cd424b7258eeac9d8e1b7/src/shell.rs#L6
Could that be the problem?

**Comment by roma0615** [comment]
Oh yeah, that was the problem. I thought I checked that before, but I guess not! Thanks
