### ISSUE TITLE
Is workspace::paths too repetitive?

### ISSUE THREAD

**Issue by matthias-t** [matthias-t/workspace#28]
https://github.com/matthias-t/workspace/blob/c9fc1135734420ab3e2e37c53de1b16618adb1f4/src/workspace.rs#L82-L104
This code could probably improved with a macro instead of all those conditonals with `continue`. But that would increase the complexity. On the other hand, this macro could also handle `Err` logging in case the verbose flag is provided. Imagine if we had to add logging to `continue` in those blocks.

**Comment by roma0615** [comment]
Yes, I think a macro would be better in this case. I don't think it would be too complicated.
