### ISSUE TITLE
`list` skips all workspaces if only 1 is corrupted

### ISSUE THREAD

**Issue by roma0615** [matthias-t/workspace#41]
In [`workspace::parse`](https://github.com/matthias-t/workspace/blob/10ee1d330bb38e9cd616a01c837ed05c86a0d065/src/workspace.rs#L79-L87), if a workspace file cannot be read, the `error!` macro is called, which calls `process::exit(1)`. This works fine for parsing single workspaces at a time (such as in `workspace::open`), but causes problems when parsing multiple files at a time, such as in `workspace::list`.

This means that if only *one* of the user's workspaces is corrupted, the user won't be able to see *any* of their workspaces when calling `ws list`.

**Comment by matthias-t** [comment]
I suggest a colored warning should be placed where the other paths are
```
workspace  C:\Users\me\my\workspace
ws         C:\Users\me\path\to\ws
other      warning: failed to [read|parse] file
```
Also, maybe it would make sense to allow deleting a workspace even though reading or parsing fails.

**Comment by matthias-t** [comment]
For that purpose we'd have to pass around `Result`s or `Option`s instead of using `exit!`

**Comment by matthias-t** [comment]
Since `workspace::all` and `workspace::get` need to return `Result`s, we'll need to make a custom error type saying wether it was a reading or parsing problem and containing the name of the workspace.

**Comment by matthias-t** [comment]
The problem is that coloring the paths and warnings makes the length of the strings change, because it counts the ansi escape characters
