### ISSUE TITLE
`edit` subcommand

### ISSUE THREAD

**Issue by matthias-t** [matthias-t/workspace#56]
Open the `toml` file for the workspace in the default editor

**Comment by matthias-t** [comment]
Here's a solution in `bash` (from [stackoverflow](https://stackoverflow.com/questions/10725238/opening-default-text-editor-in-bash)):
```bash
"${EDITOR:-vi}" ~/.workspace/NAME.toml
```
where `vi` is a POSIX-guaranteed-to-be-present fallback in case `$EDITOR` is unset. 

In PowerShell that'd be just:
```posh
~/.workspace/NAME.toml
```
Since it's different for each shell, we should add a new recognized prefix to our shell wrappers, something like `EDIT>`.

**Comment by pExeen** [comment]
This is the shortest solution I found for fish:
`set editor $EDITOR vi; eval $editor[1] ~/.workspace/NAME.toml`
