### ISSUE TITLE
Add a verbose flag

### ISSUE THREAD

**Issue by matthias-t** [matthias-t/workspace#8]
Currently, in `workspace::read_files`, we ignore files we can't read, or files where `file_type` returns an Err. This is good, but if at some point there is trouble because some files aren't read, then we can't know what went wrong. My suggestion is to add a verbose flag (`-v`, `--verbose`) that causes this type of information to be logged.

**Comment by roma0615** [comment]
That would definitely help the user. Do we know how to add flags?

**Comment by matthias-t** [comment]
With `.arg()`, see the [clap docs](https://docs.rs/clap/2.31.2/clap/)
